---
title: "4. Explorando bases"
author: "Eliezer Cavazos"
date: "2024-08-13"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lectura Archivo

```{r}
oMcDonalds = read.csv("C:\\Users\\eliez\\OneDrive\\Desktop\\Clases\\mc-donalds-menu.csv") #leer la base de datos

```


## 2. Analisis datos atipicos y normalidad

```{r}
#library(nortest)
shapiro.test(oMcDonalds$Calories)
qqnorm(oMcDonalds$Calories)
qqline(oMcDonalds$Calories)

shapiro.test(oMcDonalds$Carbohydrates)
qqnorm(oMcDonalds$Carbohydrates)
qqline(oMcDonalds$Carbohydrates)
```

## 3. Grafico de Densidad



```{r}

oCalories = oMcDonalds$Calories


y1 = min(oCalories)
y2 = max(oCalories)

q1=quantile(oCalories,0.25)  #Cuantil 1 de la variable oCalories
q3 = quantile(oCalories, 0.75)
#ri= q3-q1   #o   
ri=IQR(oCalories)    #Rango intercuartílico de oCalories

rango = q3+1.5*ri

par(mfrow=c(2,1))  #Matriz de gráficos de 2x1
boxplot(oCalories,horizontal=TRUE)
abline(v=rango,col="red")  #linea vertical en el límite de los datos atípicos o extremos

oCaloriesClean= oCalories[oCalories<rango]  #En la matriz M, quitar datos más allá de 1.5 rangos intercuartílicos arriba de q3 de la variable oCalories
summary(oCaloriesClean)
summary(oCalories)
```
```{r}
oCarboHydrates = oMcDonalds$Carbohydrates
y1 = min(oCarboHydrates)
y2 = max(oCarboHydrates)

q1=quantile(oCarboHydrates,0.25)  #Cuantil 1 de la variable oCarboHydrates
q3 = quantile(oCarboHydrates, 0.75)
#ri= q3-q1   #o   
ri=IQR(oCarboHydrates)    #Rango intercuartílico de oCarboHydrates

rango = q3+1.5*ri

par(mfrow=c(2,1))  #Matriz de gráficos de 2x1
boxplot(oCarboHydrates,horizontal=TRUE)
abline(v=rango,col="red")  #linea vertical en el límite de los datos atípicos o extremos

oCarboHydratesClean= oCarboHydrates[oCarboHydrates<rango]  #En la matriz M, quitar datos más allá de 1.5 rangos intercuartílicos arriba de q3 de la variable oCarboHydrates
summary(oCarboHydratesClean)
summary(oCarboHydrates)
```


```{r}

hist(oCaloriesClean,prob=TRUE,col=0)
x=seq(min(oCaloriesClean),max(oCaloriesClean),0.1)
y=dnorm(x,mean(oCaloriesClean),sd(oCaloriesClean))
lines(x,y,col="red")

x=seq(min(oCalories),max(oCalories),0.1)
y=dnorm(x,mean(oCalories),sd(oCalories))
lines(x,y,col="Blue")
```
```{r}

hist(oCarboHydratesClean,prob=TRUE,col=0)
x=seq(min(oCarboHydratesClean),max(oCarboHydratesClean),0.1)
y=dnorm(x,mean(oCarboHydratesClean),sd(oCarboHydratesClean))
lines(x,y,col="red")

x=seq(min(oCarboHydrates),max(oCarboHydrates),0.1)
y=dnorm(x,mean(oCarboHydrates),sd(oCarboHydrates))
lines(x,y,col="Blue")
```
## 4. Analizar Normalidad
```{r}
library(nortest)

print("Calories")
ad.test(oCalories)
ad.test(oCaloriesClean)

print("CarboHydrates")
ad.test(oCarboHydrates)
ad.test(oCarboHydratesClean)

```
## 4.2 Grafica QQPLOT
```{r}
qqnorm(oCaloriesClean)
qqline(oCaloriesClean)
```
```{r}
qqnorm(oCarboHydratesClean)
qqline(oCarboHydratesClean)
```

## 4.3 Analisis Sesgo y Curtosis
```{r}
library(e1071)
print("Calories")
skewness(oCaloriesClean) 
kurtosis(oCaloriesClean)

print("Carbohydrates")
skewness(oCarboHydratesClean) 
kurtosis(oCarboHydratesClean)
```
## 4.4 Comparar media, mediana y rango medio

```{r}
print("Calories")
summary(oCaloriesClean)
summary(oCalories)

print("Carbohydrates")
summary(oCarboHydratesClean)
summary(oCarboHydrates)
```


## 4.5 Histograma
```{r}
hist(oCaloriesClean,freq=FALSE)
lines(density(oCaloriesClean),col="red")
curve(dnorm(x,mean=mean(oCaloriesClean,sd=sd(oCaloriesClean))), from=-6, to=6, add=TRUE, col="blue",lwd=2)
```
```{r}
hist(oCarboHydratesClean,freq=FALSE)
lines(density(oCarboHydratesClean),col="red")
curve(dnorm(x,mean=mean(oCarboHydratesClean,sd=sd(oCarboHydratesClean))), from=-6, to=6, add=TRUE, col="blue",lwd=2)
```





